MFP_OrderProcessing/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static, serve
from django.conf import settings
# from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('register.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}), #serve media files when deployed
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}), #serve static files when deployed
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from . import views
from .views import OrdersListView, OrderCreate, OrderDetailView, OrderLineCreate, FulfillmentUpdate, FulfillmentView

urlpatterns = [
    path('', views.index, name='index'),
    path('orders/', OrdersListView.as_view(), name='order_list'),  # List all orders
    path('order/new/', OrderCreate.as_view(), name='order_create'),  # Create a new order
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('order/<int:pk>/orderline_create/', OrderLineCreate.as_view(), name='orderline_create'), # View details of a specific order

#     path('catalog/order_list/', views.OrdersListView.as_view(), name='order_list'),
# # mjl 7/31/2024 working on orderline page
#     path('orderline/create/', views.OrderLineCreate.as_view(), name='orderline_create'),
#     path('orderline/<int:pk>/update/', views.OrderLineUpdate.as_view(), name='orderline_update'),
# # mjl 7/30/2024 adding rows here for new order page
#     path('order/create/', views.OrderCreate.as_view(), name='order_create'),
#     path('order/<int:pk>/update/', views.OrderUpdate.as_view(), name='order_update'),

# mjl 7/31/2024 adding rows here for new staff and products page
    path('products/create/', views.ProductsCreate.as_view(), name='products_create'),
    path('products/<int:pk>/update/', views.ProductsUpdate.as_view(), name='products_update'),
    path('products/<int:pk>/delete/', views.products_delete, name='products_delete'),
    path('catalog/products_list/', views.ProductsListView.as_view(), name='products_list'),

    path('staff/create/', views.StaffCreate.as_view(), name='staff_create'),
    path('staff/<int:pk>/update/', views.StaffUpdate.as_view(), name='staff_update'),
    path('staff/<int:pk>/delete/', views.staff_delete, name='staff_delete'),
    path('catalog/staff_list/', views.StaffListView.as_view(), name='staff_list'),

    # ar 7/31 adding url route for profile page
    path('profile/', views.profile, name='profile'),
    #ar 8/5/2024 adding edit_profile view
    path('profile/edit/', views.edit_profile, name='edit_profile'),

    #ar 8/1 adding demogrpahics form view
    path('demographics_form/', views.demographics_form, name='demographics_form'),

    #for order fulfillment page
    path('orders_list/', views.orders_list, name='orders'),
    # mjl 8/10/2024 added for fulfillment page
    path('fulfillment/', views.FulfillmentView.as_view(), name='fulfillment'),
    path('fulfillment/<int:pk>/update/', views.FulfillmentUpdate.as_view(), name='fulfillment_update'),

]

catalog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse # used to generate URLs by reversing the URL patterns
import uuid

# Create your models here

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, unique=True)
    # first_name = models.TextField(max_length=500, null=True, blank=True)
    # last_name = models.TextField(max_length=500, null=True, blank=True)
    # email = models.TextField(max_length=500, null=True, blank=True)
    bio = models.TextField(max_length=500, null=True, blank=True)
    image = models.ImageField(upload_to="images/profile",
                              default="images/profile/default.png", null=True)
    private = models.BooleanField(default=True)

    def __str__(self):
        return str(self.user)

# class Customer(models.Model):
#     customer_id = models.AutoField(primary_key=True)
#     # mjl 7/30/2024 need to connect registered user to customer account trying foreign key
#     # https://docs.djangoproject.com/en/5.0/topics/auth/customizing/#extending-user
#     user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
#     # demographics_id = models.ForeignKey('Demographics', on_delete=models.CASCADE)
#     customer_first_name = models.CharField(max_length=50)
#     customer_last_name = models.CharField(max_length=50)
#     customer_email = models.EmailField(unique=True)
#     customer_phone_number = models.CharField(max_length=12)
#
#     FACULTY_OR_STAFF_CHOICES = [
#         ('Y', 'Yes'),
#         ('N', 'No'),
#     ]
#     is_faculty_or_staff = models.CharField(max_length=1, choices=FACULTY_OR_STAFF_CHOICES)

    # def get_full_customer_info(self):
    #     return {
    #         "customer_id": self.customer_id,
    #         "demographics_id": self.demographics_id,
    #         "customer_first_name": self.customer_first_name,
    #         "customer_last_name": self.customer_last_name,
    #         "customer_email": self.customer_email,
    #         "customer_phone_number": self.customer_phone_number,
    #         "faculty_or_staff": self.get_is_faculty_or_staff_display()
    #     }
class OrdersHeader(models.Model):
    order_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # mjl 8/10/2024 adding join to staff so we can assign them to orders
    staff_id = models.ForeignKey('Staff', null = True, on_delete=models.CASCADE)
    # @property  # mjl 8/10/2024 trying this in place of above code
    # def staff_id(self):
    #         return f"{self.staff_id.staff_first_name}"

    pickup_location_id = models.ForeignKey('PickupLocation', on_delete=models.CASCADE)
    order_date = models.DateField()
    # order_fill_or_shop = models.CharField(max_length=20)  mjl 7/30/2024 updating to list
    FILL_SHOP_CHOICES = [
        ('fill','Please pack my order for me'),
        ('shop',"I'll shop in store"),
    ]
    order_fill_or_shop = models.CharField(max_length=4, choices=FILL_SHOP_CHOICES)

    IS_BAG_REQUIRED_CHOICES = [
        ('Y', 'Yes please bag for me'),
        ('N', "No I'll bring my own"),
    ]
    is_bag_required = models.CharField(max_length=1, choices=IS_BAG_REQUIRED_CHOICES)
    # mjl 7/30/2024 adding null allowed so customer can enter new order without fulfillment date
    order_fulfillment_date = models.DateField(blank=True, null=True)
    ORDER_PICKUP_STATUS_CHOICES = [
        ('Y', 'Yes'),
        ('N', 'No'),
    ]
    order_pickup_status = models.CharField(max_length=1, choices=ORDER_PICKUP_STATUS_CHOICES)
    order_notification_date_1st = models.DateField(blank=True, null=True)
    order_notification_date_2nd = models.DateField(blank=True, null=True)
    order_notification_date_3rd = models.DateField(blank=True, null=True)
    ORDER_DIAPERS_CHOICES = [
        ('Y', 'Yes'),
        ('N', 'No'),
    ]
    order_diapers = models.CharField(max_length=1, choices=ORDER_DIAPERS_CHOICES)

    ORDER_PARENT_SUPPLIES_CHOICES = [
        ('Y', 'Yes'),
        ('N', 'No'),
    ]
    order_parent_supplies = models.CharField(max_length=1, choices=ORDER_PARENT_SUPPLIES_CHOICES)
    # mjl 8/10/2024 moved up from orderline
    order_notes = models.TextField(null=True, blank=True)
    def get_full_ordersheader_info(self):
        return {
            "order_id": self.order_id,
            "User_id": self.user_id,
            "staff_id": self.staff_id,
            "pickup_location_id": self.pickup_location_id,
            "order_date": self.order_date,
            "order_fill_or_shop": self.order_fill_or_shop,
            "is_bag_required": self.get_is_bag_required_display(),
            "order_fulfillment_date": self.order_fulfillment_date,
            "order_pickup_status": self.get_order_pickup_status_display(),
            "order_notification_date_1st": self.order_notification_date_1st,
            "order_notification_date_2nd": self.order_notification_date_2nd,
            "order_notification_date_3rd": self.order_notification_date_3rd,
            "order_diapers": self.get_order_diapers_display(),
            "order_parent_supplies": self.get_order_parent_supplies_display(),
            "order_notes": self.order_notes
        }

class Demographics(models.Model):
    demographics_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    # dependent_id = models.ForeignKey('Dependent', on_delete=models.CASCADE)
    # comment_id = models.ForeignKey('Comment', on_delete=models.CASCADE)
    # Changes to our ERD design made these foreign keys not necessary
    user_secondary_email = models.EmailField(unique=True, null=True, default='None')
    user_NUID = models.CharField(max_length=20, null=True, default='0')

    USER_GRAD_CHOICES = [
        ('Y', 'Yes'),
        ('N', 'No'),
    ]
    user_grad = models.CharField(max_length=1, choices=USER_GRAD_CHOICES)

    USER_AFFILIATION_CHOICES = [
        ('1', 'UNO'),
        ('2', 'UNMC'),
        ('3', 'MCC'),
    ]
    user_affiliation = models.CharField(max_length=1, choices=USER_AFFILIATION_CHOICES, null=True)

    IS_INTERNATIONAL_STUDENT_CHOICES = [
        ('Y', 'Yes'),
        ('N', 'No'),
    ]
    is_international_student = models.CharField(max_length=1, choices=IS_INTERNATIONAL_STUDENT_CHOICES)

    IS_FIRST_GEN_CHOICES = [
        ('Y', 'Yes'),
        ('N', 'No'),
    ]
    is_first_gen = models.CharField(max_length=1, choices=IS_FIRST_GEN_CHOICES)

    USER_CLASS_STANDING_CHOICES = [
        ('1', 'Freshman'),
        ('2', 'Sophomore'),
        ('3', 'Junior'),
        ('4', 'Senior'),
    ]
    user_class_standing = models.CharField(max_length=1, choices=USER_CLASS_STANDING_CHOICES, null=True)

    # mjl 8/10/2024 adding occupation field
    user_occupation = models.CharField(max_length=100, null=True)

    USER_LIVING_STATUS_CHOICES = [
        ('1', 'Off-Campus - alone'),
        ('2', 'Off-campus - With Family'),
        ('3', 'On-Campus'),
    ]
    user_living_status = models.CharField(max_length=1, choices=USER_LIVING_STATUS_CHOICES, null=True)

    USER_TRANSPORTATION_CHOICES = [
        ('1', 'Walking'),
        ('2', 'Public Transportation'),
        ('3', 'Car'),
    ]
    user_transportation = models.CharField(max_length=1, choices=USER_TRANSPORTATION_CHOICES, null=True)

    USER_EMPLOYMENT_CHOICES = [
        ('1', 'Part-Time'),
        ('2', 'Full-Time'),
        ('3', 'Not Employed'),
        ('4', 'Unable to Work')
    ]
    user_employment = models.CharField(max_length=1, choices=USER_EMPLOYMENT_CHOICES)

    # mjl 8/10/2024 updating to a choice field
    USER_ETHNICITY_CHOICES = [
        ('1', 'Black or African American'),
        ('2', 'White or Caucasian'),
        ('3', 'Hispanic or Latinx'),
        ('4', 'American Indian or Alaskan'),
        ('5', 'Asian'),
        ('6', 'Prefer Not to Say'),
    ]
    user_ethnicity = models.CharField(max_length=1, choices=USER_ETHNICITY_CHOICES)

    user_age = models.CharField(max_length=2)

    # mjl 8/10/2024 updating to a choice field
    USER_GENDER_CHOICES = [
        ('1', 'Male'),
        ('2', 'Female'),
        ('3', 'Non-Binary'),
        ('4', 'Trans'),
        ('5', 'Prefer Not to Say')
    ]
    user_gender_identity = models.CharField(max_length=1, choices=USER_GENDER_CHOICES)

    USER_MARITAL_STATUS_CHOICES = [
        ('Y', 'Yes'),
        ('N', 'No'),
    ]
    user_marital_status = models.CharField(max_length=1, choices=USER_MARITAL_STATUS_CHOICES)
    user_household_size = models.CharField(max_length=50)

    HAS_DEPENDENTS_CHOICES = [
        ('Y', 'Yes'),
        ('N', 'No'),
    ]
    has_dependents = models.CharField(max_length=1, choices=HAS_DEPENDENTS_CHOICES)
    user_number_dependents = models.CharField(null=True, max_length=50)

    USER_WGEC_CHOICES = [
        ('Y', 'Affiliated with WGEC'),
        ('N', 'No'),
    ]
    user_wgec = models.CharField(max_length=1, choices=USER_WGEC_CHOICES)
    user_zip_code = models.CharField(max_length=10)
    user_allergies = models.CharField(max_length=50)

    def get_full_demographic_info(self):
        return {
            "cuser_id": self.user_id,
            "user_secondary_email": self.user_secondary_email,
            "user_NUID": self.user_NUID,
            "user_grad": self.get_user_grad_display(),
            "user_affiliation": self.user_affiliation,
            "is_international_student": self.get_is_international_student_display(),
            "is_first_gen": self.get_is_first_gen_display(),
            "user_class_standing": self.get_user_class_standing_display(),
            "user_living_status": self.user_living_status,
            "user_transportation": self.user_transportation,
            "user_occupation": self.user_occupation, # mjl 8/10/2024 added was missing
            "user_employment": self.get_user_employment_display(),
            "user_ethnicity": self.user_ethnicity,

catalog/forms.py
from django import forms
from .models import Demographics, Profile, OrderLine, PickupLocation
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import OrdersHeader, Products
from django.forms import modelformset_factory # mjl 8/10/2024 added to resolve error after merge

def validate_age(value):
    try:
        age = int(value)
    except ValueError:
        raise ValidationError('Age must be a valid integer.')

    if not (0 <= age <= 120):
        raise ValidationError('Age must be between 0 and 120.')

def validate_NUID(value):
    if not value.isdigit() or len(value) != 8:  # Adjust length as per your requirement
        raise ValidationError('NUID must be a 8-digit number.')

def validate_zip_code(value):
    import re
    if not re.match(r'^\d{5}(-\d{4})?$', value):
        raise ValidationError('Enter a valid ZIP code.')

class DemographicsForm(forms.ModelForm):
    class Meta:
        model = Demographics
        fields = ['user_id', 'user_secondary_email','user_NUID','user_grad','user_affiliation',
                  'is_international_student','is_first_gen', 'user_class_standing',
                  'user_transportation', 'user_living_status', 'user_transportation',
                  'user_occupation', # mjl 8/10/2024 added occupation field which was missing
                  'user_employment',
                  'user_ethnicity', 'user_age', 'user_gender_identity', 'user_marital_status',
                  'has_dependents', 'user_number_dependents', 'user_wgec', 'user_zip_code', 'user_allergies',
                  'user_household_size',]
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(DemographicsForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['user_id'].initial = user.id
            self.fields['user_id'].widget = forms.HiddenInput()

        self.fields['user_age'].validators.append(validate_age)
        self.fields['user_NUID'].validators.append(validate_NUID)
        self.fields['user_zip_code'].validators.append(validate_zip_code)
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'image', 'private']

class OrderCreateForm(forms.ModelForm):
    products = forms.ModelMultipleChoiceField(
        queryset=Products.objects.all(),
        # widget=forms.CheckboxSelectMultiple ,
        widget=forms.HiddenInput(),  # mjl 8/13/2024 will this hide on Order Header page?
        required=False
    )
    quantities = forms.CharField(
        widget=forms.HiddenInput(),  # Hide the field from the user
        required=False
    )
    pickup_location_id = forms.ModelChoiceField(
        queryset=PickupLocation.objects.all(),
        label="Pickup Location",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    class Meta:
        model = OrdersHeader
        fields = ['pickup_location_id', 'order_date', 'order_fill_or_shop', 'is_bag_required', 'order_diapers', 'order_parent_supplies', 'order_notes']
    def clean(self):
        cleaned_data = super().clean()
        products = cleaned_data.get('products')
        quantities = cleaned_data.get('quantities')
        if products and not quantities:
            raise forms.ValidationError("Quantities must be provided for selected products.")
        # Parse quantities
        if quantities:
            quantities = quantities.split(',')
            if len(products) != len(quantities):
                raise forms.ValidationError("Mismatch between products and quantities.")
        return cleaned_data

class OrderLineForm(forms.ModelForm):
    class Meta:
        model = OrderLine
        fields = ['product_id', 'order_line_number', 'order_quantity_requested' ] #, 'order_notes']
        # widgets = {
        #     'order_notes': forms.Textarea(attrs={'rows': 3}),
        # }
        # mjl 8/10/2024 removing order notes to resolve merge conflict
OrderLineFormSet = modelformset_factory(OrderLine, fields=('product_id', 'order_quantity_requested'), extra=1)

catalog/templates/catalog/order_create.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Create a New Order</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        
        <button type="submit">Save Order</button>
    </form>
    
{% endblock %}

catalog/templates/catalog/order_detail.html
<!-- templates/catalog/order_detail.html -->
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>Order Details</h2>

    <h3>Order Information</h3>
    <ul>
        <li><strong>Order ID:</strong> {{ order.order_id }}</li>
        <li><strong>User:</strong> {{ order.user_id.username }}</li>
        <li><strong>Pickup Location:</strong> {{ order.pickup_location_id.pickup_location_name }}</li>
        <li><strong>Order Date:</strong> {{ order.order_date }}</li>
        <li><strong>Fill or Shop:</strong> {{ order.get_order_fill_or_shop_display }}</li>
        <li><strong>Bag Required:</strong> {{ order.get_is_bag_required_display }}</li>
        <li><strong>Fulfillment Date:</strong> {{ order.order_fulfillment_date }}</li>
        <li><strong>Pickup Status:</strong> {{ order.get_order_pickup_status_display }}</li>
        <li><strong>Notification Date 1st:</strong> {{ order.order_notification_date_1st }}</li>
        <li><strong>Notification Date 2nd:</strong> {{ order.order_notification_date_2nd }}</li>
        <li><strong>Notification Date 3rd:</strong> {{ order.order_notification_date_3rd }}</li>
        <li><strong>Diapers Required:</strong> {{ order.get_order_diapers_display }}</li>
        <li><strong>Parent Supplies Required:</strong> {{ order.get_order_parent_supplies_display }}</li>
    </ul>

    <h3>Order Lines</h3>
    {% if order.orderline_set.exists %}
        <ul>
            {% for line in order.orderline_set.all %}
                <li>
                    <strong>Product:</strong> {{ line.product_id.product_name }}<br>
                    <!--strong>Line Number:</strong> {{ line.order_line_number }}<br-->  <!--mjl 8/13-->
                    <strong>Quantity Requested:</strong> {{ line.order_quantity_requested }}<br>
                    <!--strong>Notes:</strong> {{ line.order_notes }} -->
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No order lines found for this order.</p>
    {% endif %}

    <a href="{% url 'order_create' %}">Create New Order</a>
    <a href="{% url 'order_list' %}">Back to Order List</a>

    <!-- mjl 8/15/2024 jump from Fulfillment page, need to navigate back for Superusers -->
    {% if user.is_superuser or user.is_staff %}
        <td><a href="{% url 'fulfillment' %}" class="btn btn-primary">Back to Fulfillment</a></td>
    {% endif %}

{#    <a href="{% url 'orderline_create' pk=order.order_id %}">Add Food Item</a> #}
{% endblock %}

catalog/templates/catalog/order_fulfillment.html
{% extends "catalog/base.html" %}
{% block content %}
    
    
    <h2>Orders</h2>

    {% if order_fulfillment %} 
        <table class="table table-bordered">
            <tr class="table-secondary"> 
                    <th>Order ID</th> 
                    <th>Order Date</th>
                    <th>Staff</th> 
                    <!--th>Notes</th-->
                    <th>Fill Date</th> 
                    <th>PickUp</th>
                    <th>View</th>
                    <th>Update</th>
            </tr>
            
        {% for order in order_fulfillment.all %}
            <tr class="table-secondary"> 
                    <td>{{ order.order_id }} </td> 
                    <td>{{ order.order_date }}</td>
                    <td>{{ order.staff_id.staff_first_name }} </td> 
                    <!--td>{ order.staff_id }} </td--> 
                    <!--td>{ order.order_notes }}</td-->
                    <td>{{ order.order_fulfillment_date }} </td> 
                    <td>{{ order.order_pickup_status }}</td>
            {% if user.is_superuser or user.is_staff %} 
                    <!-- mjl 8/15/2024 adding order view per teacher feedback -->
                    <td><a href="{% url 'order_detail' pk=order.pk %}" class="btn btn-primary">View</a></td>
                    <td><a href="{% url 'fulfillment_update' pk=order.pk %}" class="btn btn-primary">Edit Status</a></td> 
            {% endif %}
            </tr>
        {% empty %}
            <p>There are no orders.</p>
        {% endfor %}
        
        </table>
    {% else %} 
        <p>There are no orders.</p> 
    {% endif %}
    
{% endblock %}

catalog/templates/catalog/order_list.html
{% extends "catalog/base.html" %}
{% block content %}
    <h2>My Orders</h2>
    <ul>
        {% for order in orders %}
            <li>
                <a href="{% url 'order_detail' pk=order.pk %}">
                    Order #{{ order.order_id }} - {{ order.order_date }} - {{ order.order_pickup_location }}
                </a>
            </li>
        {% empty %}
            <p>You have no orders.</p>
        {% endfor %}
    </ul>
    <a href="{% url 'order_create' %}">Create New Order</a>
{% endblock %}

catalog/templates/catalog/orderline_create.html
<!-- templates/catalog/orderline_form.html -->
{% extends "catalog/base.html" %}

{% block content %}
    
  <h2>Add Products to Order</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.management_form }}
    {% for form in form %}
      {{ form.as_p }}
    <!--mjl 8/13 trying to show list of products being selected -->    
    <!--p>{ form.product_id.product_name }} { form.order_quantity_requested }}</p-->
        
    {% endfor %}
    <button type="submit" name="action" value="add_and_stay">Add Product and Continue</button>
    <p></p>
    <p>Select from our available products above.  Once you've selected all the products you want hit this button: </p>
    <p></p>
    <button type="submit" name="action" value="submit_and_redirect">Complete Order</button>
  </form>
    
{% endblock %}

catalog/templates/catalog/ordersheader_form.html
{% extends "catalog/base.html" %} 
{% load crispy_forms_tags %} 
{% load crispy_forms_filters %} 
 
{% block content %} 
    {% if perms.catalog.edit_fulfillment %} 
        <form action="" method="POST"> 
            <!--{{ from.as_p }}  mjl 7/30/2024 found used in online research -->
            {% csrf_token %} 
            {{ form|crispy }} 
 
            <input type="submit" value="Submit"/> 
        </form> 
    {% else %} 
        You do not have permission to access this feature 
        <a href="{% url 'order_fulfillment' %}">Close</a> 
    {% endif %} 
{% endblock %} 

catalog/templates/catalog/profile.html
{% extends "catalog/base.html" %}
{% load static %}

{% block content %}
  <style>
    .container {
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }

    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 20px;
    }

    .profile-container {
      background-color: #f9f9f9;
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    .profile-section {
      margin-bottom: 20px;
    }

    .profile-section h2 {
      margin-top: 0;
    }

    .profile-section img {
      max-width: 200px;
      height: auto;
      border-radius: 8px;
    }

    .btn-secondary {
      margin: 10px 5px;
    }
  </style>

  <div class="container">
    <div class="header">
      <h1>User Profile</h1>
      <div>
        <a href="{% url 'edit_profile' %}" class="btn btn-secondary">Edit Profile</a>
        <a href="{% url 'index' %}" class="btn btn-secondary">Back to Home</a>
      </div>
    </div>
    
    <div class="profile-container">
      <div class="profile-section">
        <h2>Basic Information</h2>
        <p><strong>Username:</strong> {{ user.username }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>First Name:</strong> {{ user.first_name }}</p>
        <p><strong>Last Name:</strong> {{ user.last_name }}</p>
      </div>

      <div class="profile-section">
        <h2>Profile Information</h2>
        <p><strong>Bio:</strong> {{ profile.bio }}</p>
        <p><strong>Profile Image:</strong> <img src="{{ profile.image.url }}" alt="Profile Image"></p>
        <p><strong>Private:</strong> {{ profile.private }}</p>
      </div>

      <div class="profile-section">
        <h2>Demographics Information</h2>
        <p><strong>Secondary Email:</strong> {{ demographics.user_secondary_email }}</p>
        <p><strong>NUID:</strong> {{ demographics.user_NUID }}</p>
        <p><strong>Graduate:</strong> {{ demographics.get_user_grad_display }}</p>
        <p><strong>Affiliation:</strong> {{ demographics.user_affiliation }}</p>
        <p><strong>International Student:</strong> {{ demographics.get_is_international_student_display }}</p>
        <p><strong>First Generation:</strong> {{ demographics.get_is_first_gen_display }}</p>
        <p><strong>Class Standing:</strong> {{ demographics.get_user_class_standing_display }}</p>
        <p><strong>Occupation:</strong> {{ demographics.user_occupation }}</p>
        <p><strong>Living Status:</strong> {{ demographics.user_living_status }}</p>
        <p><strong>Transportation:</strong> {{ demographics.user_transportation }}</p>
        <p><strong>Employment:</strong> {{ demographics.get_user_employment_display }}</p>
        <p><strong>Ethnicity:</strong> {{ demographics.user_ethnicity }}</p>
        <p><strong>Age:</strong> {{ demographics.user_age }}</p>
        <p><strong>Gender Identity:</strong> {{ demographics.user_gender_identity }}</p>
        <p><strong>Marital Status:</strong> {{ demographics.get_user_marital_status_display }}</p>
        <p><strong>Household Size:</strong> {{ demographics.user_household_size }}</p>
        <p><strong>Dependents:</strong> {{ demographics.get_has_dependents_display }}</p>
        <p><strong>Number of Dependents:</strong> {{ demographics.user_number_dependents }}</p>
        <p><strong>WGEC:</strong> {{ demographics.get_user_wgec_display }}</p>
        <p><strong>Zip Code:</strong> {{ demographics.user_zip_code }}</p>
        <p><strong>Allergies:</strong> {{ demographics.user_allergies }}</p>
      </div>
    </div>
  </div>
{% endblock %}